steps:
- name: 'python:3.7'
  entrypoint: python3
  args: ['-m', 'venv', '/workspace/venv']
- name: 'install requirements to venv'
  entrypoint: "/workspace/venv/bin/pip"
  args: ['install', '-r', 'requirements.txt']
- name: 'python:3.7'
  entrypoint: "/workspace/venv/bin/python"
  args: ['./manage.py', 'collectstatic', '--noinput']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"