steps:
- name: 'python:3.7'
  entrypoint: python3
  args: ['-m', 'venv', 'venv']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ["source", "venv/bin/activate"]
- name: 'python:3.7'
  entrypoint: python3
  args: ['-m', 'pip', 'install', '-r', 'requirements.txt']
- name: 'python:3.7'
  entrypoint: python3
  args: ['./manage.py', 'collectstatic', '--noinput']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"